# skilltracker-services/payment-service/docker-compose.yml

services:
  postgres-payment:
    container_name: postgres-payment-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: payment_service_db
      POSTGRES_USER: ${POSTGRES_USER:-paymentservice}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-paymentservice123}
    ports:
      - "5435:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-paymentservice} -d payment_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - skilltracker-network

  payment-service:
    build:
      context: ../..
      dockerfile: ./skilltracker-services/payment-service/Dockerfile
    image: skilltracker/payment-service:latest
    container_name: payment-service
    ports:
      - "8087:8087"
    environment:
      SERVER_PORT: 8087
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-payment:5432/payment_service_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-paymentservice}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-paymentservice123}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8082/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8081
    depends_on:
      postgres-payment:
        condition: service_healthy
    networks:
      - skilltracker-network

networks:
  skilltracker-network:
    external: true

volumes:
  postgres_payment_data:
