package com.amalitech.task.service.model;

import com.amalitech.task.service.model.enums.SubmissionStatus;
import com.amalitech.task.service.model.submission.SubmissionAnswer;
import com.amalitech.task.service.model.feedback.SubmissionFeedback;

import io.hypersistence.utils.hibernate.type.json.JsonType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Type;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA Entity representing a user's attempt (submission) at a specific {@link Task}.
 * <p>
 * This entity is the core transactional record for the SkillBoost platform's evaluation
 * pipeline. It stores the user's answer, tracks the evaluation status, and holds the
 * final polymorphic score and feedback generated by the AI agents. The use of JSONB
 * mapping via {@code JsonType} allows for flexible, polymorphic storage of the
 * {@link SubmissionAnswer} and {@link SubmissionFeedback} structures, accommodating
 * various task types (coding, essay, MCQ) without requiring a rigid, single-table
 * schema for all answer types.
 */
@Entity
@Table(name = "task_submissions",
        indexes = {
                @Index(name = "idx_submission_user_task", columnList = "user_id, task_id"),
                @Index(name = "idx_submission_status", columnList = "is_correct")
        })
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class TaskSubmission {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id", nullable = false)
    private Task task;

    /**
     * Stores structured, polymorphic answer JSON.
     */
    @Type(JsonType.class)
    @Column(columnDefinition = "jsonb", nullable = false)
    private SubmissionAnswer answer;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private SubmissionStatus status;

    /**
     * Stores structured, polymorphic feedback JSON.
     */
    @Type(JsonType.class)
    @Column(columnDefinition = "jsonb")
    private SubmissionFeedback feedback;

    private Boolean isCorrect;

    private Integer scoreEarned;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime submittedAt;

    @Column
    private LocalDateTime evaluatedAt;

    /**
     * Lifecycle method executed before the entity is persisted for the first time.
     * <p>
     * This method ensures that if the status field is not explicitly set, it defaults
     * to {@link SubmissionStatus#PENDING}, guaranteeing a clear initial state for
     * the asynchronous evaluation workflow.
     */
    @PrePersist
    protected void onCreate() {
        if (this.status == null) {
            this.status = SubmissionStatus.PENDING;
        }
    }
}