# skilltracker-services/feedback-service/docker-compose.yml

services:
  postgres-feedback:
    container_name: postgres-feedback-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: feedback_service_db
      POSTGRES_USER: ${POSTGRES_USER:-feedbackservice}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-feedbackservice123}
    ports:
      - "5434:5432"
    volumes:
      - postgres_feedback_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-feedbackservice} -d feedback_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - skilltracker-network

  feedback-service:
    build: .
    image: skilltracker/feedback-service:latest
    container_name: feedback-service
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-feedback:5432/feedback_service_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-feedbackservice}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-feedbackservice123}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8082/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8081
    depends_on:
      postgres-feedback:
        condition: service_healthy
    networks:
      - skilltracker-network

networks:
  skilltracker-network:
    external: true

volumes:
  postgres_feedback_data:
