package com.amalitech.task.service.model.feedback.impl;

import com.amalitech.task.service.model.feedback.SubmissionFeedback;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Concrete implementation of {@link SubmissionFeedback} designed to store the comprehensive,
 * multi-dimensional evaluation results and suggestions for an Essay task submission.
 * <p>
 * This structure captures the detailed AI evaluation results including completeness,
 * accuracy, clarity, and depth assessments as generated by the essay evaluation prompt.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
public class EssaySubmissionFeedback implements SubmissionFeedback {

    private Evaluation evaluation;

    /**
     * The main evaluation container matching the AI prompt structure.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Evaluation {
        private CategoryEvaluation completeness;
        private CategoryEvaluation accuracy;
        private CategoryEvaluation clarity;
        private CategoryEvaluation depth;
        private OverallEvaluation overall;
    }

    /**
     * Evaluation details for a single assessment category.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class CategoryEvaluation {
        private Double score;
        private Integer percentage;
        private String feedback;
        private List<CriteriaMet> criteriaMet;
        private List<String> strengths;
        private List<String> improvements;
    }

    /**
     * Assessment of individual evaluation criteria.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class CriteriaMet {
        private String criterion;
        private Boolean met;
        private String feedback;
    }

    /**
     * Overall evaluation summary and scoring.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class OverallEvaluation {
        private Double totalScore;
        private Double percentage;
        private Double xpEarned;
        private Double maxXP;
        private Boolean passed;
        private String summary;
        private List<String> keyStrengths;
        private List<String> keyImprovements;
        private String nextSteps;
    }

    private Double grammarScore;
    private Double relevanceScore;
    private String toneAnalysis;
    private List<FeedbackSuggestion> suggestions;

    /**
     * Legacy: Represents a specific, actionable suggestion for improvement.
     * @deprecated Use the detailed evaluation structure instead.
     */
    @Data
    @Deprecated
    public static class FeedbackSuggestion {
        private String originalText;
        private String suggestedChange;
        private String comment;
    }
}